version: '3.1'

services:
  credit-calculator:
    image: credit-calculator
    build: ./
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  sms-service:
    image: aeren/credit-calculator:latest
    ports:
      - "9000:9000"

  rabbitmq:
    image: rabbitmq:3.8.3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
